package com.grupocuatro.academiaidiomas.forms;

import com.grupocuatro.academiaidiomas.models.Alumno;
import com.grupocuatro.academiaidiomas.services.AlumnoServiceImpl;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luish
 */
public class AlumnosForm extends javax.swing.JFrame {

    /**
     * Creates new form AlumnosForm
     */
    private final AlumnoServiceImpl alumnoService = new AlumnoServiceImpl();

    public AlumnosForm() {
        initComponents();
        cargarAlumnosEnTabla();
    }

    //Método para que se cargue la lista de alumnos nada más inicializar el formulario:
    private void cargarAlumnosEnTabla() {
        List<Alumno> alumnos = alumnoService.listarAlumnos();

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (Alumno alumno : alumnos) {
            Object[] fila = {
                alumno.getId(),
                alumno.getNombre(),
                alumno.getApellidos(),
                alumno.getEdad(),
                alumno.getDni(),
                alumno.getDireccion(),
                alumno.getTelefono()
            };
            modelo.addRow(fila);
        }

        if (modelo.getRowCount() == 0) {
            modelo.addRow(new Object[]{"", "", "", "", "", "", "", ""});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackButtom = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ActualizarButton = new javax.swing.JButton();
        AddAlumno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Edad", "DNI", "Direccion", "Telefono", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BackButtom.setText("Volver");
        BackButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtomActionPerformed(evt);
            }
        });

        DeleteButton.setText("Borrar");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Edad", "DNI", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        ActualizarButton.setText("Actualizar");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });

        AddAlumno.setText("Añadir");
        AddAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButtom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActualizarButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddAlumno)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButtom)
                    .addComponent(DeleteButton)
                    .addComponent(ActualizarButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddAlumno)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtomActionPerformed
        this.dispose();

        MenuForm menuForm = new MenuForm();
        menuForm.setVisible(true);
    }//GEN-LAST:event_BackButtomActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            Boolean isSelected = (Boolean) jTable1.getValueAt(i, 7);
            if (isSelected != null && isSelected) {
                Integer id = (Integer) jTable1.getValueAt(i, 0);
                if (id != null) {
                    AlumnoServiceImpl service = new AlumnoServiceImpl();
                    boolean borrado = service.eliminarAlumno(id);

                    if (borrado) {
                        ((javax.swing.table.DefaultTableModel) jTable1.getModel()).removeRow(i);

                    }
                }
                break;
            }

        }
        cargarAlumnosEnTabla();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            Boolean isSelected = (Boolean) jTable1.getValueAt(i, 7);
            if (isSelected != null && isSelected) {
                Integer id = (Integer) jTable1.getValueAt(i, 0);

                String nombre = (String) jTable1.getValueAt(i, 1);
                String apellidos = (String) jTable1.getValueAt(i, 2);
                Integer edad = (Integer) jTable1.getValueAt(i, 3);
                String dni = (String) jTable1.getValueAt(i, 4);
                String direccion = (String) jTable1.getValueAt(i, 5);
                String telefono = (String) jTable1.getValueAt(i, 6);

                if (id != null) {
                    AlumnoServiceImpl service = new AlumnoServiceImpl();
                    Alumno alumno = new Alumno(nombre, apellidos, edad, dni, direccion, telefono);
                    boolean actualizado = service.actualizarAlumno(id, alumno);

                    if (actualizado) {
                        ((javax.swing.table.DefaultTableModel) jTable1.getModel()).removeRow(i);

                    }
                }
                break;
            }

        }
        cargarAlumnosEnTabla();
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    private void AddAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAlumnoActionPerformed

        AlumnoServiceImpl service = new AlumnoServiceImpl();

        String nombre = (String) jTable2.getValueAt(0, 0);
        String apellidos = (String) jTable2.getValueAt(0, 1);
        Integer edad = (Integer) jTable2.getValueAt(0, 2);
        String dni = (String) jTable2.getValueAt(0, 3);
        String direccion = (String) jTable2.getValueAt(0, 4);
        String telefono = (String) jTable2.getValueAt(0, 5);

        Alumno alumno = new Alumno(nombre, apellidos, edad, dni, direccion, telefono);
        service.agregarAlumno(alumno);
        cargarAlumnosEnTabla();
    }//GEN-LAST:event_AddAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JButton AddAlumno;
    private javax.swing.JButton BackButtom;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
