package com.grupocuatro.academiaidiomas.forms;

import com.grupocuatro.academiaidiomas.models.Colegio;
import com.grupocuatro.academiaidiomas.models.Curso;
import com.grupocuatro.academiaidiomas.models.Matricula;
import com.grupocuatro.academiaidiomas.services.AlumnoServiceImpl;
import com.grupocuatro.academiaidiomas.services.ColegioServiceImpl;
import com.grupocuatro.academiaidiomas.services.CursoServiceImpl;
import com.grupocuatro.academiaidiomas.services.MatriculacionServiceImpl;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luish
 */
public class InfoAlumnoForm extends javax.swing.JFrame {

    private final ColegioServiceImpl colegioService = new ColegioServiceImpl();
    private final MatriculacionServiceImpl matriculaService = new MatriculacionServiceImpl();
    private final CursoServiceImpl cursoService = new CursoServiceImpl();

    public InfoAlumnoForm(Integer alumnoID, String nombre, String apellidos, Integer edad, String dni, String direccion, String telefono, Integer colegioId) {
        initComponents();
        Alumno.setText("Alumno: " + nombre + " " + apellidos);
        if (colegioId == null) {
            Colegio.setText("Colegio: No asignado");
            DireccionColegio.setText("Dirección: No disponible");
        } else {
            cargarColegio(colegioId);
        }
        cargarNotasEnTabla(alumnoID);

    }

    private void cargarColegio(Integer id) {

        Colegio colegio = colegioService.mostrarColegio(id);

        if (colegio == null) {
            Colegio.setVisible(false);
            DireccionColegio.setVisible(false);
        } else {
            String nombreColegio = colegio.getNombre();
            String direccionColegio = colegio.getDireccion();
            Colegio.setText("Colegio: " + nombreColegio);
            DireccionColegio.setText("Dirección: " + direccionColegio);
        }

    }

    private void cargarNotasEnTabla(int idAlumno) {
        // Obtener las notas y los cursos del alumno
        List<Integer> notas = matriculaService.listarNotas(idAlumno);
        List<Curso> cursosDelAlumno = cursoService.obtenerCursosPorAlumno(idAlumno);

        // Inicializamos el modelo de la tabla y la limpiamos
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        System.out.println("Cursos: " + cursosDelAlumno.size());
        System.out.println("Notas: " + notas.size());
        // Comprobamos que las listas de cursos y notas tengan el mismo tamaño
        if (notas.size() == cursosDelAlumno.size()) {
            // Recorremos los cursos y asociamos cada curso con su respectiva nota
            for (int i = 0; i < cursosDelAlumno.size(); i++) {
                Curso curso = cursosDelAlumno.get(i);
                Integer nota = notas.get(i);

                // Obtenemos el idioma y el nivel del curso
                String idioma = curso.getIdioma();
                String nivel = curso.getNivel();

                // Añadimos una fila a la tabla con la información del curso y la nota
                model.addRow(new Object[]{idioma, nivel, nota});
            }
        } else {
            // Si las listas no coinciden en tamaño, lanzamos un error o manejamos la situación
            System.err.println("El número de cursos y notas no coincide.");
        }
    }

    /**
     * private void cargarNotasEnTabla(int idAlumno) { List<Integer> notas =
     * matriculaService.listarNotas(idAlumno);
     *
     * DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
     * model.setRowCount(0);
     *
     * for (Integer nota : notas) { model.addRow(new Object[]{"Curso
     * desconocido", "", nota}); }
    }
     */
    /**
     * public void cargarCursoTabla() {
     *
     * List for (int i = 0; i < model.getRowCount(); i++) { // Aquí actualizamos
     * la segunda columna de la tabla, pero dejamos intactas las demás columnas
     * model.setValueAt("Nuevo valor", i, 1); // Actualiza la segunda columna
     * model.setValueAt(notas.get(i), i, 2); // Actualiza la columna de la nota
     * (columna 3, índice 2) } }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Alumno = new javax.swing.JLabel();
        Colegio = new javax.swing.JLabel();
        DireccionColegio = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Curso", "Nivel", "Nota"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Alumno.setText("Alumno");

        Colegio.setText("Colegio");

        DireccionColegio.setText("Direccion Colegio");

        BackButton.setText("Volver");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DireccionColegio, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Colegio, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(BackButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alumno)
                    .addComponent(BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Colegio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DireccionColegio)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        AlumnosForm alumnosForm = new AlumnosForm();
        alumnosForm.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alumno;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Colegio;
    private javax.swing.JLabel DireccionColegio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
