package com.grupocuatro.academiaidiomas.forms;

import com.grupocuatro.academiaidiomas.models.Colegio;
import com.grupocuatro.academiaidiomas.services.AlumnoServiceImpl;
import com.grupocuatro.academiaidiomas.services.ColegioServiceImpl;

/**
 *
 * @author luish
 */
public class InfoAlumnoForm extends javax.swing.JFrame {

    private final ColegioServiceImpl colegioService = new ColegioServiceImpl();
    private int id;

    public InfoAlumnoForm(Integer alumnoID, String nombre, String apellidos, Integer edad, String dni, String direccion, String telefono, Integer colegioId) {
        initComponents();
        Alumno.setText("Alumno: " + nombre + " " + apellidos);
        if (colegioId == null) {
            Colegio.setText("Colegio: No asignado");
            DireccionColegio.setText("Dirección: No disponible");
        } else {
            cargarHistorialEnTabla(colegioId);
        }

    }

    private void cargarHistorialEnTabla(Integer id) {

        Colegio colegio = colegioService.mostrarColegio(id);

        if (colegio == null) {
            Colegio.setVisible(false);
            DireccionColegio.setVisible(false);
        } else {
            String nombreColegio = colegio.getNombre();
            String direccionColegio = colegio.getDireccion();
            Colegio.setText("Colegio: " + nombreColegio);
            DireccionColegio.setText("Dirección: " + direccionColegio);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Alumno = new javax.swing.JLabel();
        Colegio = new javax.swing.JLabel();
        DireccionColegio = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Curso", "Nota"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Alumno.setText("Alumno");

        Colegio.setText("Colegio");

        DireccionColegio.setText("Direccion Colegio");

        BackButton.setText("Volver");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DireccionColegio, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Colegio, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(BackButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alumno)
                    .addComponent(BackButton))
                .addGap(23, 23, 23)
                .addComponent(Colegio)
                .addGap(12, 12, 12)
                .addComponent(DireccionColegio)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        AlumnosForm alumnosForm = new AlumnosForm();
        alumnosForm.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alumno;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Colegio;
    private javax.swing.JLabel DireccionColegio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
