/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupocuatro.academiaidiomas.forms;

import vista.VistaCurso;

/**
 *
 * @author luish
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlumnosOpen = new javax.swing.JButton();
        profesoresButton = new javax.swing.JButton();
        matriculasButton = new javax.swing.JButton();
        cursosButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AlumnosOpen.setText("Mostrar Alumnos");
        AlumnosOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnosOpenActionPerformed(evt);
            }
        });

        profesoresButton.setText("Mostrar Profesores");
        profesoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesoresButtonActionPerformed(evt);
            }
        });

        matriculasButton.setText("Mostrar Matrículas");
        matriculasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculasButtonActionPerformed(evt);
            }
        });

        cursosButton.setText("Mostrar Cursos");
        cursosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursosButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("SELECCIONA UNA TABLA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profesoresButton)
                .addGap(18, 18, 18)
                .addComponent(AlumnosOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matriculasButton)
                .addGap(26, 26, 26)
                .addComponent(cursosButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursosButton)
                    .addComponent(matriculasButton)
                    .addComponent(AlumnosOpen)
                    .addComponent(profesoresButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlumnosOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnosOpenActionPerformed
        this.dispose();

        AlumnosForm alumnosForm = new AlumnosForm();
        alumnosForm.setVisible(true);
    }//GEN-LAST:event_AlumnosOpenActionPerformed

    private void profesoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesoresButtonActionPerformed
        this.dispose();
        ProfesoresForm profesoresForm = new ProfesoresForm();
        profesoresForm.setVisible(true);
    }//GEN-LAST:event_profesoresButtonActionPerformed

    private void matriculasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculasButtonActionPerformed
        this.dispose();
        MatriculaForm matriculaForm = new MatriculaForm();
        matriculaForm.setVisible(true);
    }//GEN-LAST:event_matriculasButtonActionPerformed

    private void cursosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursosButtonActionPerformed
        this.dispose();
        VistaCurso vistaCurso = new VistaCurso();
        vistaCurso.setVisible(true);
    }//GEN-LAST:event_cursosButtonActionPerformed
    
    //metodo para volver a hacer visible este formulario:
    private void visibleForm(){
        this.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlumnosOpen;
    private javax.swing.JButton cursosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton matriculasButton;
    private javax.swing.JButton profesoresButton;
    // End of variables declaration//GEN-END:variables
}
